---
- name: Prepare web and nfs servers
  hosts: webservers, nfs
  become: yes
  tasks:
    - name: Ensure Python3 is installed
      yum:
        name: python3
        update_cache: yes
        state: present

- name: update LB server
  hosts: lb, db
  become: yes
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: Ensure Python3 is installed
      apt:
        name: python3
        state: present