pipeline {
    agent any
    environment {
      ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
    }
    parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }
    stages {
      stage ('Initial Cleanup') {
        steps {
          dir("${WORKSPACE}"){
            deleteDir()
          }
        }
      }
      stage ('Checkout SCM') {
        steps {
          git branch: 'main', url: 'https://github.com/mrdankuta/ansible-config-mgt.git'
        }
      }
      stage ('Prepare Ansible for Execution') {
        steps {
          sh 'echo ${WORKSPACE}'
          sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'
        }
      }
      stage ('Run Ansible Playbook') {
        steps {
          ansiblePlaybook become: true, credentialsId: 'ansible_target_1', disableHostKeyChecking: true, installation: 'jensible', inventory: 'inventory/${inventory}', playbook: 'playbooks/site.yml'
        }
      }
      stage ('Cleanup After Build') {
        steps {
          cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
        }
      }
    }
}