---
- hosts: all
- name: Include dynamic variables
  tasks:
    import_playbook: ../static-assignments/common.yml
    Include: ../dynamic-assignments/env-vars.yml
    tags:
      - always

- hosts: webservers
- import_playbook: ../static-assignments/webservers.yml
